/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haocai_ffmpegtest_VideoUtils */

#ifndef _Included_com_haocai_ffmpegtest_VideoUtils
#define _Included_com_haocai_ffmpegtest_VideoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haocai_ffmpegtest_VideoUtils
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_haocai_ffmpegtest_VideoUtils_decode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_haocai_ffmpegtest_VideoUtils
 * Method:    render
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_haocai_ffmpegtest_VideoUtils_render
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_haocai_ffmpegtest_VideoUtils
 * Method:    sound
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_haocai_ffmpegtest_VideoUtils_audioDecode
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
